### ISSUE TITLE
VirGL support on Windows hosts upstreamed?

### ISSUE THREAD

**Issue by emxd** [kjliew/qemu-3dfx#109]
Hello,

as you're probably aware QEMU now has VirGL working on Windows. That said, I'm not sure where this is coming from. Looking at the Gitlab issues tracker (https://gitlab.com/qemu-project/qemu/-/issues/1461), it doesn't look like your patch was integrated with the upstream? Looking at the QEMU changelog site (https://wiki.qemu.org/ChangeLog), I didn't see any mention of it. And yet if I try Stefan Weil's latest build, virgl is working.

Do you happen to know if VirGL is now upstreamed? Or if this is just some patch that's integrated with Weil's builds?

Edit: Or is it the patch mentioned by Marc-André Lureau in the issues tracker discussion?

**Comment by emxd** [comment]
Just tried master and VirGL works. So it is upstream and not just Stefan Weil builds. But I take it that it's not your patches?

**Comment by kjliew** [comment]
Isn't that wonderful?? 😇 Much of the upstream work was done by Marc-André Lureau. He's on qemu-3dfx YouTube subscribers' list, so he knew very well about this project. VirGL support on Windows host was committed since April 2023.

My initial patches wasn't really doing much to get VirGL on Windows host. What it mostly does is a workaround by rerouting the need of `libepoxy/EGL` to simply `libepoxy/GL` and getting rid of `libgbm` false dependency. Over time, the ecosystem picked up those improvements by themselves, `MSYS2/mingw-w64` added EGL support for `libepoxy` and upstream QEMU decoupled `libgdm` by improving its libs dependency check.

My patches are still required for VirGL support on macOS host with SDL2 OpenGL backend. It is much simpler than other alternatives that resort to `libANGLE/EGL` to obtain VirGL support on macOS host. Anyway, with such complexity the later can be considered "more future-proof" as `libANGLE/EGL` realize OpenGL with Apple Metal while SDL2 OpenGL simply depends on deprecated Apple OpenGL.

Upstreaming `libANGLE/EGL` is rather involved and has been stalled for quite some time. Where as SDL2 OpenGL, though simple, is at risk of Apple OpenGL deprecation. Well, it's all up to QEMU devs, macOS remains the only platform deprived of VirGL support.

**Comment by emxd** [comment]
I read something about VirGL working on Discord, but I'm quite surprised that the commits were added already back in April. And ***\*yes\****, it is wonderful... between this, hyper-v dxgkrnl and the virtio-gpu-win drivers I've got some new things to try out.
