### ISSUE TITLE
How to build WineD3D for windows 9x?

### ISSUE THREAD

**Issue by RobertSpir** [kjliew/qemu-3dfx#12]
the wineD3D libraries available for example at https://fdossena.com/?p=wined3d/index.frag are not compatible with windows 9x, it is possible to built compatible version, or is somewhere some compatible version available?

**Comment by kjliew** [comment]
I hope that the demand for Windows 9x support could be directed to [WineHQ](https://www.winehq.org/) or whoever the owner of the link you just referred.

Otherwise, become a donor supporting this project https://github.com/kjliew/qemu-3dfx#donation and in return receive QEMU-enhanced WineD3D libraries for Win98/2K/ME/XP.

**Comment by RobertSpir** [comment]
Ok, so I started with something more simple, I'm trying to run quake 2 demo with opengl, but it fails on SetPixelFormat, qemu log is 
```
mesapt: DLL loaded
glcntx: ChoosePixelFormat() fmt 0x0c
glcntx: PixFmt 0x0c nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x0c ret 0
glcntx: ChoosePixelFormat() fmt 0x0c
glcntx: PixFmt 0x0c nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x0c ret 0
mesapt: DLL unloaded
```

**Comment by kjliew** [comment]
@RobertSpir Please keep on topic or open another issue.

Legacy OpenGL games require GL extensions capping. It can be done either from Host or Guest side. I will provide an example on an on-topic new issue.

**Comment by gflorin414** [comment]
Will you give the source code for a donation or just the libraries?
