### ISSUE TITLE
Android Emulator Hypervisor Driver for AMD Processors support

### ISSUE THREAD

**Issue by MrPepka** [kjliew/qemu-3dfx#64]
Hi
Are you planning to add support for this driver? This is a hardware acceleration driver for Windows designed for AMD processors (alternative to WHPX and HAXM). There is also a QEMU that supports this driver
https://github.com/qemu-gvm/qemu-gvm

**Comment by kjliew** [comment]
Likely not, for the following reasons:
1. It is designed for AVD with 3rd-party kernel-mode driver (gvm.sys).
2. Modern OSes would not give in hypervisor capabilities to 3rd-party solution because the OS may depend on virtualization to protect its critical core and security hardened runtime. The OS native user-space APIs is the best and proven way for shared accesses to hypervisor capabilities.
3. It is not available in QEMU upstream.

The 3D acceleration from qemu-3dfx does not depend on hypervisor support. It works with TCG and HAXM in general and likely any accelerators in QEMU. However, when specific accelerators are available such as WHPX and KVM, certain optimization can be enabled to eliminate approximation in forwarded API semantics for speed or compatibility.
