### ISSUE TITLE
enhanced D3D library compile?

### ISSUE THREAD

**Issue by michaeljkkim** [kjliew/qemu-3dfx#73]
Hi, where can I get the source code for this enhanced d3d library in order to compile it myself? I assumed that the one mentioned in the donation thing was precompiled?

**Comment by kjliew** [comment]
They are WineD3D libraries and WINE source code is always available at [WineHQ](https://www.winehq.org), for those who wish to compile by themselves. There is also a forum at WineHQ in case you have any questions.

**Comment by michaeljkkim** [comment]
But did you edit these libraries in any way? I was asking because certain people are saying that you are violating GPLv2 by selling these custom libraries

**Comment by kjliew** [comment]
Please consult a qualified legal advisor on Open Source licenses. The donation to support the project and Game Preservation is **NOT A SALE** and fully in compliance with the Open Source licenses.

**Comment by michaeljkkim** [comment]
> Please consult a qualified legal advisor on Open Source licenses. The donation to support the project and Game Preservation is **NOT A SALE** and fully in compliance with the Open Source licenses.

So we can technically get everything up and running to 100% without the compiled libraries you would be providing?

**Comment by kjliew** [comment]
> So we can technically get everything up and running to 100% without the compiled libraries you would be providing?

Given enough time, devotion & determination, **WHY NOT**?!! This may not be the answer to your question as the answer may vary depends on who you asked. There is hardly a definite answer to such a question, and "YES" or "NO" is a subjective matter that serves no ground for legal dispute in the Open Source Court.

**Comment by casasfernando** [comment]
@kjliew just to clarify because I find the answer above a bit confusing.
If one compile WineD3D stock libraries without any patching and install them in the guest OS will they work with your patched qemu version or they will require patching?

I'm asking because I would avoid going down that rabbit hole if in the end a patch is needed for them to work with this project.

Thanks!

**Comment by kjliew** [comment]
> If one compile WineD3D stock libraries without any patching and install them in the guest OS will they work with your patched qemu version or they will require patching?

Go to [WineHQ](https://www.winehq.org) and shoot the same question to Wine developers. If you believe that this project is in violation of any Open Source licenses, then the copyright holders shall be notified if they would proceed with legal actions against this project.

**Comment by casasfernando** [comment]
@kjliew sorry if I didn’t express myself correctly. I’m not interested into the licensing stuff mentioned here. Just want to know if the stock libraries will work or not. That’s all.

if you say yes I will spend time building them. If you say no I will just use my time on something else. :)

**Comment by kjliew** [comment]
@casasfernando Exercise some **\*common sense\***, or it will be up to you to figure it out. Google can be your best friend, it is not very difficult to find simple answer as simple as this all by yourself.

**Comment by casasfernando** [comment]
I guess you just answered. They will not.

Thanks

**Comment by wilsontulus** [comment]
Seemingly great lib at the outside but unfortunately the dev is **greedy enough** that he even called obtaining those "exclusive" libraries donating, not buying. I mean, people will not even sure if he's even going to give the source code after we "donate" him? There's even a chance it could even be a scam, by any means, only the binaries are given and not the source code. 

**By any means, massive L for this dev.**

**Comment by gflorin414** [comment]
I can tell you it does not work. Followed every step to the letter. Everything works up until you install the video and sound drivers mentioned in the wiki. They just don't work. And it probably isn't going to work even after you get the totally non-purchased binaries deserved only by people who donate the minimum sum. And the audacity to ask for money in order to (maybe) give me a binary that may or may not do what it's supposed to do? Who do you take me for? Your binary will not run on my PC, friend. I wouldn't run it even if YOU paid me.
