### ISSUE TITLE
USB Gamepad patch

### ISSUE THREAD

**Issue by casasfernando** [kjliew/qemu-3dfx#74]
@kjliew are you planning to release the qemu patch for usb gamepad device support as well?

I managed to compile your patched qemu version and it works nice but I just discovered that it doesn't include usb gamepad device support.

Thanks.

**Comment by kjliew** [comment]
Check out the [reference in the Wiki](https://github.com/kjliew/qemu-3dfx/wiki/QEMU-USB-Gamepad) where to find the patch. Next, write in QEMU mailing lists to have QEMU developers support USB Gamepad device model without `libusb`. You can also make a case at QEMU mailing lists for any violation of Open Source licenses regarding QEMU.

Otherwise, make a small donation to support the project and Game Preservation and in return receive QEMU binary package for your platform of choice for QEMU USB Gamepad and everything else included. Details at https://github.com/kjliew/qemu-3dfx#donation

**Comment by casasfernando** [comment]
@kjliew thanks for replying so fast and don’t get me wrong but you sound a bit defensive. Sorry if I said something that upset you, it was not my intention. I’m not interested in any licensing stuff.

I checked the patch you mentioned in reddit and will try to use it against qemu 6.2.0. I already saw that it needs some tweaking to get it to build because it’s for an old version of qemu but I hopefully may be able to work that out.
Also saw that you are linking to another page with information about DS4 codes and so on. Would that be needed to adapt the reddit patch to this project?

Regarding donating I would do so but in all honesty I’m not interested in just getting the binaries. I would rather like to have the source code of the different patches as well. Would that be included?

Thanks

**Comment by kjliew** [comment]
I am quoting from my friend @stilett0 from VOGONS
https://www.vogons.org/viewtopic.php?p=948442#p948442

**Comment by kjliew** [comment]
@casasfernando Never worry about me getting upset. The project is meant to have FUN😊. I answered all inquiries including refutal of violation in Open Source licenses in candid manner.

A video meme mimic the same quote from my friend @stilett0 from VOGONS in STAR WARS fantasies. HAVE FUN!
https://youtu.be/xXrdhvNTcsY?t=738
