### ISSUE TITLE
wglSetPixelFormatWINE -- Missing (launching DirectX 8.1 game demo via WineD3D fails)

### ISSUE THREAD

**Issue by misutoneko** [kjliew/qemu-3dfx#8]
Hi,

I tested some old game demos that have a very low probability of ever working in Wine "as is" (because of SF protection).
There were a couple of DX8.1 ones that failed to launch (using WineD3D wrapper in the guest).
In the qemu console, I see this error message:
 mesapt:   query_ext: wglSetPixelFormatWINE -- Missing

I don't know if this is something that is simply currently unimplemented, or maybe dependent on WineD3D version?
The demos in question:
 GT Legends
 Xpand Rally September demo
Please note that they might also need d3d9.dll, even though they are supposed to be for DX8.1.
Also, GT Legends does work in VirtualBox I think.

LM20 host, WinXP guest, using opengl32.dll and newest WineD3D from https://fdossena.com/?p=wined3d/index.frag
My qemu-3dfx and stubs are quite recent (3b968d4) and built against qemu-5.2.0.

**Comment by kjliew** [comment]
`mesapt: query_ext: wglSetPixelFormatWINE -- Missing` -- This is not an error. It is OK because it runs on legit Microsoft implementation of WIN32 APIs, not WINE implementation of WIN32 APIs.
Both games work with caveats:
- Xpand Rally did not work on Win2K/XP. It crashed with `crash.log` - `FATAL ERROR : Cannot find valid frame buffer format !`. But I think it had to do with the Starforce DRM driver which installed silently on first run.
- Xpand Rally works on Win98/ME. On first run, it showed "Protection System" dialog application installed successfully and wanted to reboot.
![XpandRally](https://user-images.githubusercontent.com/56374095/103742723-25af0e80-4fb0-11eb-9513-1036995dabea.png)
- GT Legends has no mouse cursor in the menu. This makes it hard to navigate the options as one has to blindly move the mouse and observe the highlighted options. This is an issue for any games expecting GDI cursor to remain visible on top of OpenGL/Direct3D screen. Once into the race, the game plays well.
![GTLegends](https://user-images.githubusercontent.com/56374095/103742753-3069a380-4fb0-11eb-9015-d1ad92532441.png)

**Comment by misutoneko** [comment]
Thank you, that's encouraging :D
So it's probably something to do with my setup. Just thought to check here first, to see if this is a WineD3D version related problem or something like that.

**Comment by kjliew** [comment]
Note that non-Steam and unpatched versions of the games (incl. demos) are **Garbage** on Wine AppDB.
GT Legends - https://appdb.winehq.org/objectManager.php?sClass=application&iId=3906
Xpand Rally - https://appdb.winehq.org/objectManager.php?sClass=application&iId=2809
