### ISSUE TITLE
What about upstreaming this project to qemu?

### ISSUE THREAD

**Issue by User-3090** [kjliew/qemu-3dfx#81]
Since you seem very dedicated to maintaining this in the foreseeable future and there is rust based 3dfx support coming to Linux, wouldn't it be cool to have this project merged with upstream qemu?

Wouldn't that make it available to many more people more easily, generating more use, visibilty, community, and donations?

**Comment by kjliew** [comment]
The short & simple answer is -- this is a hack -- QEMU does not want it. The enterprise nature of QEMU, being the backbone of Linux virtualization, re-animating EOL'ed and R.I.P. legacy Windows OSes out of their graves for retro gaming simply become jokes to be laughed at. The GOLD at enterprise clouds are more attractive than the paltry of **"$59.99 for just 3 Games"** .🤣 And for the folks on Apple Silicon macOS, Parallel Desktop is **"cheaper"** .🤣

Sorry to be mean about "the other camp" again ... For what they had created, they are **\*absolutely STUPID\*** for games. DOSBox is absolutely superb for DOS games, but it stops there. With the pleas of retro Windows gaming falling on deaf ears from VMware/VirtualBox/etc. the **\*RETARDED "long live PCem"\*** fans/followers wanted it to fill the void, pumped & bluffed all the ways and eventually it exploded.

There is little to no hope of this project to be accepted upstream. But not all is lost, it's been GPL'ed similar to QEMU. Anyone with lots of time & patience is free to take the project and upstream it, for those would otherwise believe it can be made into upstream. QEMU devs already knew about what happens here, they are free to merge the project if they like it. Anyone is also free to produce a build and share it with retro gaming community. Unlike "the other camp" **\*STUPID distortion of GPL\***, there is no such thing called "hostile fork" or any restriction in distributing development builds.

I had given the same answers at VOGONS in the past.
https://www.vogons.org/viewtopic.php?p=685136#p685136
https://www.vogons.org/viewtopic.php?p=853421#p853421
(... any concept of glide passthrough won't do a thing for Direct3D) This is correct🤣, neither would **\*CENSORED\*** for the FOOLS who believe in **\*NO CPU virtualization and NO GPU acceleration\*** .🤣
https://www.vogons.org/viewtopic.php?p=791428#p791428

**Comment by User-3090** [comment]
Ok, thanks.
