### ISSUE TITLE
Question: DirectX Passthrough instead of WineD3D conversion?

### ISSUE THREAD

**Issue by hughobrien** [kjliew/qemu-3dfx#95]
Firstly thank you so much @kjliew for your excellent project. I've really enjoyed playing with it. You have incredible knowledge, decades of experience I imagine!

As we know, the guest passes Glide calls to the host, which then renders them host-side using OpenGlide. However in your excellent videos you show the use of WineD3D on the **Guest** to convert D3D calls to OpenGL and pass OpenGL through to the host for rendering.

I assume there's a good reason, but as I am a complete novice when it comes to graphics APIs, I must ask: Is there a reason this is better than passing the D3D calls directly to the host, and letting the host's WineD3D render them?

Some pros I see: Less CPU use on the guest, less concern cross-compiling WineD3D for old platforms.

Cons: I have no idea and beg for enlightenment.

Thanks again!

**Comment by kjliew** [comment]
Thanks for the question. Everything you mentioned makes some sense in theory. Someone just needs to put that theory in implementation to really figure out the pros and cons. And, some background history of how this project get started. It all started with just Glide APIs pass-through. OpenGL is shockingly similar to Glide in the semantics, so it was just a natural instinct to apply the same learnings and expand it to cover OpenGL. Direct3D was an after-thought considering the following reasons:
- Direct3D is relatively a much more complex APIs than Glide and OpenGL due to COM interfaces.
- DirectX/Direct3D programming resources & documentation was relatively scarce without corporate-backed MSDN subscriptions. It is getting better nowadays though.
- Implementation outside of Windows could be unstable & inconsistent. AFAIK, Gallium9 in Linux only deals with d3d9, DXVK/Vulkan only deals with d3d9-d3d12 and DXVK/MoltenVK isn't quite a stable solution yet.
- Try to keep things simple, without too much platform-specific intertwining for something hobbyist in nature.

Passing D3D calls directly to host is technically feasible and simpler if the project only wanted to support modern Windows 10/11 without the concerns for cross-platform playability. Personally, this project aimed to achieve cross-platform playability for retro gaming similar to QEMU cross-platform portability.

So that inherently made WineD3D the right candidate of choice in theory with its DirectX standard compliant implementation from ddraw1-7 to d3d12. Though in reality, anything beyond d3d10 seems to be broken with OpenGL backend. Fortunately everything beyond d3d10 isn't really that much of a concern for "Retro" gaming yet.

There is also a potential hybrid approach by passing through `wined3d.dll` exported calls, if that's what you really meant to say "let the host's WineD3D render them". And you're right on the pros, less CPU use on the guest. There is another big pros, that OpenGL/Vulkan buffer objects can be completely reside on the host in persistent storage mapping for further performance optimization on modern GPUs. Wine 8.x is doing something in this direction.

The cons, `wined3d.dll` exported calls aren't really a stable interface, so if someone chooses to go down this path, then there are lots of work to deal with Wine versions progression or simply lock on specific version of Wine and do backporting patches. The value of keeping up with Wine versions progression is games compatibility and leverages the knowledge base already existed in Wine AppDB. Upstream Wine rarely made any efforts in backporting fixes.

Virtualization also brings a new paradigm of thoughts compared to traditional emulation mindsets. Less guest CPU use is typically a good thing for CPU emulation. It is still a good thing in CPU virtualization but the benefits diminish significantly in VM exits. So having any particular APIs wrapped in the host or guest isn't really matter that much as long as the implementation finds ways to batch up the workload to offset the expensive VM exits.

Lastly, allow me to make a few corrections. I was as noob as everyone else when starting the project. I bought used copies of books & literatures in OpenGL programming specifically for legacy OpenGL without Shading Language in modern era of graphics programming. Lots of reading, Googling and online research. As noob and down to earth as I was, at least I am not being foolish enough to feel great about modern Core i9-13900K or Ryzen 7950X emulating Pentium II 300MHz and the **Accuracy \*BS\* in emulation**.

**Comment by hughobrien** [comment]
Thanks for your thoughtful response! 

I hadn't thought about the 'exits' problem, of course anything that breaks the execution pipeline is going to hurt perf! What I was suggesting was that the guest use a version of `wine3d` that only provided stubs, with actual execution happening on the host's libraries, but the version alignment you mentioned sounds like a real pain in practice, I hadn't considered how much stability the OpenGL interface was providing.

I'm in agreement with you about perf, it's is a feature in and of itself, and I look forward to being able to turn a RPI4 or steam deck or Xbox into a win98/winxp gaming machine. In the distant future maybe we can have WebGPU and qemu run retro games on demand like [Bellard does with Win2k](https://bellard.org/jslinux/vm.html?url=win2k.cfg&mem=192&graphic=1&w=1024&h=768) and [others](https://copy.sh/v86/?profile=windows98) have also tried.

A final question, if I may: Do you think if QEMU had finished the work on the emulated [rage 128](https://www.emaculation.com/forum/viewtopic.php?t=10356) (giving it full 3d support, etc.) that your API passthrough method would still give better performance? My intuition is that passthough would still be better as it avoids several layers of complexity.

**Comment by kjliew** [comment]
Discussion in knowledge sharing has always been welcome!

Steam Deck should be a great win98/winxp machine with qemu-3dfx. It is just an AMD mobile platform and virtualization is supported right out of box. Valve shipped SteamOS based on ArchLinux and its kernel and MESA stacks are pretty much standard. If the built-in game controller is recognized by SDL2, then even the Steam Deck game controller will work with QEMU featuring qemu-3dfx. The Zen2+ with custom Radeon RDNA dGPU on the SteamDeck are both very capable at Win98/WinXP VMs and easily beat out anything less than Pentium III 800MHz + Geforce 3 in d3d8/9. I don't have a Steam Deck myself, the perf estimate was extrapolated from Ryzen 5 2500U with Vega Graphics.

For non-x86 camp, I think nothing beats out Apple Silicon yet. The M1/M2 CPUs remain the best for QEMU TCG workloads emulating x86. User-space emulation Box64/FEX/Wine-CE are currently more usable than QEMU full system emulation, when the demand on CPU perf outweighs what is possible with TCG dynarec. However, I do foresee the future on Foreign Architecture Virtualization that native CPU is capable of VMENTER/VMEXIT in and out of foreign architecture execution states be it x86, ARM, POWER or RISCV completely or partially accelerated by hardware. It seems that Intel is losing the grip on x86 instruction sets or perhaps Intel themselves have been in dire need of reinventing x86 to jettison the x86 legacy baggage to compete more favorably at power-performance level.

I hope you don't mind the discussion being vocal and direct. Rage 128 emulation is going to be hard and I have no idea why anyone haven't been enough trying. Even the simple Cirrus CL-GD5446 took years to finish in what it is today in QEMU and yet it is not very performant. Bochs DISPI, QXL and VirtIO are simpler and deliver much better performance than any chip emulation. The register level hardware modeling is paying huge penalty in expensive VM exits. Perhaps, it is solely focus on Mac99 emulation and haven't thought of the future of virtualization. Unless there is breakthrough in hypervisor that enables exit-less register level emulation, API passthrough will always give better performance by allowing more opportunity in batching. Rage 128 is a Direct3D7/OpenGL 1.2 class hardware, so even in its 100% complete 2D/3D emulation, its capabilities and performance are simply no match for WineD3D/MESAGL that rightfully delivers Direct3D9 SM 3.0+ and OpenGL 4.6 on all contemporary GPUs from Intel, AMD and NVIDIA.

IMHO, there is always a false perception of emulating hardware accurately such that existing drivers just work. Well, those who harbor such beliefs may have overestimated the accuracy of published documentation, especially for the complexity of 3D acceleration in GPUs. I think the smart guys at Google knew it pretty well that ChromeOS Crostini VM is fully in VirtIO implementation and they also spearhead the VirtIO Venus for Vulkan API. The results have been proven greater with well-spec VirtIO interface and paying the software efforts in bringing up the drivers. If the folks doing Rage 128 emulation in QEMU aimed at bringing accelerated OpenGL to Mac99 emulation for Mac games, I think many would be disappointed. They are better off getting the PC ports running on Apple M1/M2 with qemu-3dfx as of today.
